//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoParts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Запчасть
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Запчасть()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public int Id { get; set; }
        public string Наименование { get; set; }
        public string Марка_авто { get; set; }
        public string Модель_авто { get; set; }
        public string Производитель { get; set; }
        public int кол_во { get; set; }
        public long цена { get; set; }
        public int Id_Склад { get; set; }
    
        public virtual Склад Склад { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ> Заказ { get; set; }
    }
}
