//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoParts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int Id { get; set; }
        public int Id_Клиент { get; set; }
        public int Id_Сотрудник { get; set; }
        public int Id_Запчасть { get; set; }
    
        public virtual Запчасть Запчасть { get; set; }
        public virtual Клиент Клиент { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
